### ISSUE TITLE
Add support for new local env

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [slateci/slateci-localdev-cli#5]
Something like:
```yaml
envs:
  local:
    api:
      hostname: <hostname>
      port: 30007
      protocol: http
      token: <token>
```
